[rospy.client][INFO] 2024-07-19 02:28:03,666: init_node, name[/messagepublisher_37915_1721381283616], pid[37915]
[xmlrpc][INFO] 2024-07-19 02:28:03,668: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2024-07-19 02:28:03,668: Started XML-RPC server [http://ubuntu:38195/]
[rospy.impl.masterslave][INFO] 2024-07-19 02:28:03,669: _ready: http://ubuntu:38195/
[rospy.init][INFO] 2024-07-19 02:28:03,669: ROS Slave URI: [http://ubuntu:38195/]
[rospy.registration][INFO] 2024-07-19 02:28:03,670: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2024-07-19 02:28:03,671: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2024-07-19 02:28:03,770: registered with master
[rospy.rosout][INFO] 2024-07-19 02:28:03,771: initializing /rosout core topic
[rospy.rosout][INFO] 2024-07-19 02:28:03,779: connected to core topic /rosout
[rospy.simtime][INFO] 2024-07-19 02:28:03,781: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2024-07-19 02:28:03,790: 0
[rospy.internal][INFO] 2024-07-19 02:28:04,006: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2024-07-19 02:28:04,792: 1
[rosout][INFO] 2024-07-19 02:28:05,792: 2
[rosout][INFO] 2024-07-19 02:28:06,792: 3
[rosout][INFO] 2024-07-19 02:28:07,792: 4
[rosout][INFO] 2024-07-19 02:28:08,791: 5
[rosout][INFO] 2024-07-19 02:28:09,791: 6
[rosout][INFO] 2024-07-19 02:28:10,792: 7
[rosout][INFO] 2024-07-19 02:28:11,792: 8
[rosout][INFO] 2024-07-19 02:28:12,888: 9
[rosout][INFO] 2024-07-19 02:28:13,792: 10
[rosout][INFO] 2024-07-19 02:28:14,792: 11
[rosout][INFO] 2024-07-19 02:28:15,792: 12
[rosout][INFO] 2024-07-19 02:28:16,792: 13
[rosout][INFO] 2024-07-19 02:28:17,791: 14
[rosout][INFO] 2024-07-19 02:28:18,792: 15
[rosout][INFO] 2024-07-19 02:28:19,792: 16
[rosout][INFO] 2024-07-19 02:28:20,791: 17
[rosout][INFO] 2024-07-19 02:28:21,792: 18
[rosout][INFO] 2024-07-19 02:28:22,792: 19
[rosout][INFO] 2024-07-19 02:28:23,791: 20
[rosout][INFO] 2024-07-19 02:28:24,791: 21
[rosout][INFO] 2024-07-19 02:28:25,792: 22
[rosout][INFO] 2024-07-19 02:28:26,792: 23
[rosout][INFO] 2024-07-19 02:28:27,792: 24
[rosout][INFO] 2024-07-19 02:28:28,792: 25
[rosout][INFO] 2024-07-19 02:28:29,792: 26
[rosout][INFO] 2024-07-19 02:28:30,791: 27
[rosout][INFO] 2024-07-19 02:28:31,792: 28
[rosout][INFO] 2024-07-19 02:28:32,793: 29
[rosout][INFO] 2024-07-19 02:28:33,792: 30
[rosout][INFO] 2024-07-19 02:28:34,792: 31
[rosout][INFO] 2024-07-19 02:28:35,791: 32
[rosout][INFO] 2024-07-19 02:28:36,791: 33
[rospy.internal][INFO] 2024-07-19 02:28:37,214: topic[/information] adding connection to [/messagesubscriber], count 0
[rosout][INFO] 2024-07-19 02:28:37,793: 34
[rosout][INFO] 2024-07-19 02:28:38,792: 35
[rosout][INFO] 2024-07-19 02:28:39,792: 36
[rosout][INFO] 2024-07-19 02:28:40,792: 37
[rosout][INFO] 2024-07-19 02:28:41,792: 38
[rosout][INFO] 2024-07-19 02:28:42,796: 39
[rosout][INFO] 2024-07-19 02:28:43,791: 40
[rosout][INFO] 2024-07-19 02:28:44,792: 41
[rosout][INFO] 2024-07-19 02:28:45,791: 42
[rosout][INFO] 2024-07-19 02:28:46,798: 43
[rosout][INFO] 2024-07-19 02:28:47,792: 44
[rosout][INFO] 2024-07-19 02:28:48,792: 45
[rosout][INFO] 2024-07-19 02:28:49,792: 46
[rosout][INFO] 2024-07-19 02:28:50,792: 47
[rosout][INFO] 2024-07-19 02:28:51,792: 48
[rosout][INFO] 2024-07-19 02:28:52,793: 49
[rosout][INFO] 2024-07-19 02:28:53,792: 50
[rosout][INFO] 2024-07-19 02:28:54,792: 51
[rosout][INFO] 2024-07-19 02:28:55,802: 52
[rosout][INFO] 2024-07-19 02:28:56,792: 53
[rosout][INFO] 2024-07-19 02:28:57,791: 54
[rosout][INFO] 2024-07-19 02:28:58,791: 55
[rosout][INFO] 2024-07-19 02:28:59,792: 56
[rosout][INFO] 2024-07-19 02:29:00,792: 57
[rosout][INFO] 2024-07-19 02:29:01,792: 58
[rosout][INFO] 2024-07-19 02:29:02,792: 59
[rosout][INFO] 2024-07-19 02:29:03,792: 60
[rosout][INFO] 2024-07-19 02:29:04,792: 61
[rosout][INFO] 2024-07-19 02:29:05,792: 62
[rosout][INFO] 2024-07-19 02:29:06,791: 63
[rosout][INFO] 2024-07-19 02:29:07,792: 64
[rosout][INFO] 2024-07-19 02:29:08,792: 65
[rosout][INFO] 2024-07-19 02:29:09,791: 66
[rosout][INFO] 2024-07-19 02:29:10,792: 67
[rosout][INFO] 2024-07-19 02:29:11,792: 68
[rosout][INFO] 2024-07-19 02:29:12,792: 69
[rosout][INFO] 2024-07-19 02:29:13,791: 70
[rosout][INFO] 2024-07-19 02:29:14,791: 71
[rosout][INFO] 2024-07-19 02:29:15,791: 72
[rosout][INFO] 2024-07-19 02:29:16,792: 73
[rosout][INFO] 2024-07-19 02:29:17,792: 74
[rosout][INFO] 2024-07-19 02:29:18,791: 75
[rosout][INFO] 2024-07-19 02:29:19,796: 76
[rosout][INFO] 2024-07-19 02:29:20,793: 77
[rosout][INFO] 2024-07-19 02:29:21,791: 78
[rosout][INFO] 2024-07-19 02:29:22,791: 79
[rosout][INFO] 2024-07-19 02:29:23,898: 80
[rosout][INFO] 2024-07-19 02:29:24,791: 81
[rosout][INFO] 2024-07-19 02:29:25,791: 82
[rosout][INFO] 2024-07-19 02:29:26,793: 83
[rosout][INFO] 2024-07-19 02:29:27,791: 84
[rosout][INFO] 2024-07-19 02:29:28,791: 85
[rosout][INFO] 2024-07-19 02:29:29,792: 86
[rospy.internal][INFO] 2024-07-19 02:29:29,917: topic[/rosout] removing connection to /rosout
[rospy.rosout][ERROR] 2024-07-19 02:29:30,815: Unable to report rosout: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 165, in get_param_cached
    return rospy.impl.paramserver.get_param_server_cache().get(resolved_key)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/paramserver.py", line 177, in get
    raise KeyError(key)
KeyError: '/rosout_disable_topics_generation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/rosout.py", line 91, in _rosout
    disable_topics_ = rospy.get_param_cached("/rosout_disable_topics_generation", False)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 490, in get_param_cached
    return _param_server.get_param_cached(param_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 168, in get_param_cached
    code, msg, value = self.target.subscribeParam(rospy.names.get_caller_id(), rospy.core.get_node_uri(), resolved_key)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

[rosout][INFO] 2024-07-19 02:29:30,792: 87
[rospy.rosout][ERROR] 2024-07-19 02:29:31,795: Unable to report rosout: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 165, in get_param_cached
    return rospy.impl.paramserver.get_param_server_cache().get(resolved_key)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/paramserver.py", line 177, in get
    raise KeyError(key)
KeyError: '/rosout_disable_topics_generation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/rosout.py", line 91, in _rosout
    disable_topics_ = rospy.get_param_cached("/rosout_disable_topics_generation", False)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 490, in get_param_cached
    return _param_server.get_param_cached(param_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 168, in get_param_cached
    code, msg, value = self.target.subscribeParam(rospy.names.get_caller_id(), rospy.core.get_node_uri(), resolved_key)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

[rosout][INFO] 2024-07-19 02:29:31,791: 88
[rospy.rosout][ERROR] 2024-07-19 02:29:32,794: Unable to report rosout: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 165, in get_param_cached
    return rospy.impl.paramserver.get_param_server_cache().get(resolved_key)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/paramserver.py", line 177, in get
    raise KeyError(key)
KeyError: '/rosout_disable_topics_generation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/rosout.py", line 91, in _rosout
    disable_topics_ = rospy.get_param_cached("/rosout_disable_topics_generation", False)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 490, in get_param_cached
    return _param_server.get_param_cached(param_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 168, in get_param_cached
    code, msg, value = self.target.subscribeParam(rospy.names.get_caller_id(), rospy.core.get_node_uri(), resolved_key)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

[rosout][INFO] 2024-07-19 02:29:32,792: 89
[rospy.rosout][ERROR] 2024-07-19 02:29:33,794: Unable to report rosout: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 165, in get_param_cached
    return rospy.impl.paramserver.get_param_server_cache().get(resolved_key)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/paramserver.py", line 177, in get
    raise KeyError(key)
KeyError: '/rosout_disable_topics_generation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/rosout.py", line 91, in _rosout
    disable_topics_ = rospy.get_param_cached("/rosout_disable_topics_generation", False)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 490, in get_param_cached
    return _param_server.get_param_cached(param_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 168, in get_param_cached
    code, msg, value = self.target.subscribeParam(rospy.names.get_caller_id(), rospy.core.get_node_uri(), resolved_key)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

[rosout][INFO] 2024-07-19 02:29:33,792: 90
[rospy.core][INFO] 2024-07-19 02:29:34,522: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2024-07-19 02:29:34,524: cannot unregister with master due to network issues
[rospy.internal][INFO] 2024-07-19 02:29:34,524: topic[/information] removing connection to /messagesubscriber
[rospy.impl.masterslave][INFO] 2024-07-19 02:29:34,525: signal-2
[rospy.core][INFO] 2024-07-19 02:29:35,125: signal_shutdown [atexit]
